[package]
name = "rustylinks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1"
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.9.22"
chrono = "0.4.26"
